export const CREATE_ORDER_LIST = "CREATE_ORDER_LIST";
// ADMIN
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
export const DELETE_ORDER = "DELETE_ORDER";
export const EDIT_ORDER = "EDIT_ORDER";
