export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const LIKE_PRODUCT = "LIKE_PRODUCT";
export const DISLIKE_PRODUCT = "DISLIKE_PRODUCT";
